---
- name: Block module sample play execution
  hosts: localhost
  gather_facts: False

  tasks:
     - block:
        - name: listing /home directory
          command: "ls /home"
          register: home_out

        - name: listing /mnt directory
          command: "ls /mnt"
          register: mnt_out

        - name: listing /tmp directory
          command: "ls /tmp"
          register: tmp_out
       ignore_errors: True

     - name: Printing /home directory contents
       debug:
         var: home_out.stdout_lines

     - name: Printing /mnt directory contents
       debug:
         var: mnt_out.stdout_lines

     - name: Printing /tmp directory contents
       debug:
         var: tmp_out.stdout_lines
---
- name: installing httpd on centos and rocky linux
  hosts: linux
  become: true

  tasks:
    - block:
       - name: Install httpd on CentOS distribution
         yum:
           name: httpd
           state: present
         notify: start httpd
      when: ansible_distribution == "CentOS"

    - block:
       - name: Install chrony on RedHat distribution
         yum:
           name: chrony
           state: present
         notify: start chronyd
      when: ansible_distribution == "Rocky"

  handlers:
    - name: start httpd
      service:
        name: httpd
        state: started
      ignore_errors: True

    - name: start chronyd
      service:
        name: chronyd
        state: started
      ignore_errors: True

---
- name: installing httpd on centos and rocky linux
  hosts: linux
  become: true

  tasks:
    - block:
       - name: Install httpd on CentOS distribution
         yum:
           name: httpd
           state: present

       - name: start httpd
         service:
           name: httpd
           state: started
         ignore_errors: True

      when: "'web' in group_names"

    - block:
       - name: Install chrony on Rocky distribution
         yum:
           name: chrony
           state: present

       - name: start chronyd
         service:
           name: chronyd
           state: started
         ignore_errors: True

      when: ansible_distribution == "Rocky"
---
- name: Verify if epel-release is installed
  shell: rpm -q epel-release
  register: epel_installed
  failed_when: false

- name: Epel Repo installation
  block:
    - name: Package installation
      shell: rpm -i --nodigest "{{ epel_repo_url }}"

    - name: restart httpd
      service:
        name: httpd
        state: restarted

  when: epel_installed.rc != 0

---
- name: check if epel-release is installed
  command: "rpm -q --queryformat '%{VERSION}' epel-release"
  register: epel_version
  when: epel_installed.rc == 0

- name: Gpel Repo installation
  block:
    - name: Package installation
      shell: rpm -i --nodigest "{{ gpel_repo_url }}"

    - name: restart httpd
      service:
        name: httpd
        state: restarted

  when: epel_installed.rc == 0 and epel_version.stdout != '97.76.0.13'
      
