---
- name: Delete multiple files in a directory using find module
  hosts: localhost
  become: true

  vars:
    my_dir: "/tmp/a/b"

  tasks:
    - name: collect files
      ansible.builtin.find:
        paths: "{{ my_dir }}"
        hidden: true
        recurse: true
        file_type: any
      register: collected_files

    - name: Printing all debug output
      ansible.builtin.debug:
        var: collected_files

    - name: Removing collected files
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ collected_files.files }}"
      
    - name: Find Files ends with audit.log.51...150 range for R8
        find:
          paths: "{{ audit_log_dir}}"
          patterns: 'audit\.log\.(5[1-9]|[6-9][0-9]|1[0-4][0-9]|150)$'
          use_regex: yes
          file_type: file
        register: old_files
        
    - name: Removing Found files for R8
        file:
          path: "{{ item.path }}"
          state: absent
        with_items: "{{ old_files.files }}"
