---
- name: Guided practice
  hosts: centosstream7
  tasks:
    - name: Copy the file to remote servers and update selinux context
      copy:
        src: /etc/ansible/playbooks/testloop.yml
        dest: /tmp/
        owner: root
        group: root
        mode: '0755'
        setype: samba_share_t
        
    - name: Create a file using copy module
      ansible.builtin.copy:
        dest: "{{ filename }}"
        content: |
           "This is not an empty file"
        
    - name: Copying a file from /tmp directory
      become: true
      copy:
        src: /tmp/testfile.txt
        dest: /tmp
        owner: testuser
        group: testuser
        mode: 0644
        backup: yes

   - name: Take existing auditd.conf file
      copy:
          src: /etc/audit/auditd.conf
          dest: /etc/audit/auditd.conf_{{ansible_date_time.date}}.bkp
          backup: yes
          remote_src: yes

   - name: Copy multiple configuration files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - { src: /tmp/file1.conf, dest: /etc/app/file1.conf }
        - { src: /tmp/file2.conf, dest: /etc/app/file2.conf }
      args:
        owner: root   # Common owner for all files
        group: root   # Common group for all files
        mode: '0644'  # Common permissions for all files
---
- name: Copy multiple files
  hosts: localhost
  tasks:
    - name: copy multiple files using copy module
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/tmp/destdir"
        owner: root
        mode: '0644'
      with_fileglob:
        - "/tmp/sourcedir/*.json"
    - name: List system files to copy
      find:
        path: /var/tmp/log/
        patterns: "systems*"
        register: systems_logs

    - name: Copy System files
      copy:
        src: "{{item.path}}"
        dest: /var/log/
        remote_src: yes
      loop:
      - { path: '/path/to/file1' }
      - { path: '/path/to/file2' }
      - { path: '/path/to/file3' }

