---
- name: Guided practice
  hosts: centosstream7, rockylinux9
  tasks:
     - name: Add a line to /tmp/testloop.yml file
      lineinfile:
        path: /tmp/testloop.yml
        line: 'This line added from Ansible playbook'
        state: present
        
     - name: Editing ssh config file and replacing PasswordAuthentication from "no" to "yes"
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        state: present
        line: PasswordAuthentication yes
        validate: 'sshd -t -f %s'
        notify:
          - Restarting sshd

  handlers:
    - name: Restarting sshd
      service:
        name: sshd
        state: restarted
