---
- hosts: centosstream7
  become: true
  become_user: root
  tasks:
    - name: Include the apache installation file
      include_tasks: tasks/configure_apache.yml
      vars:
        package: httpd
        service: httpd
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Import firewall confuguration file
      import_tasks: tasks/configure_firewall.yml
      vars:
        firewall_pkg: firewalld
        firewall_svc: firewalld
        rule:
          - http
          - https

    - name: Import the index file
      import_tasks: tasks/create_index.yml
      vars:
        dest_file: /var/www/html/index.html
        
- name: Import connectivity test playbook
  import_playbook: tasks/check_connectivity.yml
  vars:
    url: 'http://192.168.43.235'
