---
- name: Fet df -h out
  hosts: LinuxClient2

  tasks:
    - name: Execute shell module to fetch df -h
      shell: "df -h"
      register: data_out

    - name: Display /data fs usage
      debug:
        var: data_out.stdout_lines

    - name: Get the PID of auditd
      command: pidof auditd
      register: auditd_pid

    - name: Display the PID of auditd
      debug:
        msg: "The PID of auditd is {{ auditd_pid.stdout }}"

    - name: Fetch file content
      shell: "tail -10 /tmp/testloop.yml"
      register: testloop_data

    - name: Displays last 10 files from /tmp/testloop.yml after addding new line
      debug:
        msg: "{{ testloop_data.stdout.split('\n') }}"

    - name: Capturing current working directory(S) file(s) list
      ansible.builtin.shell: 'ls -lrt *'
      register: command_output

    - name: Listing files under current directory
      ansible.builtin.debug:
        var: command_output.stdout_lines
---
- name: Environment demo
  hosts: localhost
  # 'printenv' command will print available list of environments
  tasks:
    - name: display HOME
      ansible.builtin.debug:
        msg: "{{ lookup('env', 'HOME') }}"

---
- name: Fetching os distribution and name
  hosts: localhost

  tasks:
    - name: Printing os dist and name
      debug:
        msg:
          - "my os distribution is: {{ ansible_system }}"
          - "my os name is: {{ ansible_distribution }}"
          - "my os family is: {{ ansible_os_family }}"
          - "my mount pionts are: {{ ansible_mounts }}"
