---
- name: Install and uninstall pkgs
  hosts: localhost
  gather_facts: False

  tasks:
    - name: Install {{ pkg }} package
      yum:
        name: "{{ pkg }}"
        state: "{{ pkg_state }}"

    # command line arguments
    # ansible-playbook install_uninstall_pkgs.yml -e "{'pkg':'httpd', 'pkg_state':'present'}"
    # ansible-playbook install_uninstall_pkgs.yml -e "pkg=httpd pkg_state=present"

---
- name: Defining vars for Command Line Argument
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Printing x & y values
      debug:
        msg:
          - "x value is: {{x}}"
          - "y value is: {{y}}"

   # Extra variables
   # ansible-playbook cmd_line_arg_extra_vars.yml -e "'x':'xstring', 'y'='ystring'"
   # ansible-playbook cmd_line_arg_extra_vars.yml -e "{'x':'xstring', 'y':'ystring'}"
   # ansible-playbook cmd_line_arg_extra_vars.yml -e "{'x':[1,2,3], 'y':['a', 'b', 'c']}"
   # ansible-playbook cmd_line_arg_extra_vars.yml -e "{'x':{'a':'1', 'b':'2'}, 'y':['c':'3', 'd':'4', 'c':'5']}"
   # ansible-playbook cmd_line_arg_extra_vars.yml -e "@create_variables.yml"
   # ansible-playbook cmd_line_arg_extra_vars.yml -e "@create_json_variables.yml"

[root@ansible-control-node playbooks]# cat /etc/ansible/playbooks/advanced_1/create_variables.yml
---
    a: 5
    b: 6
    c: 8
    pkgs:
      'linux': 'top'
      'aix': 'mop'
      'solaris': 'cop'
    x: ['abc', 5, 7.8, {'name':'ganesh'}]
    y: {'a':5, 'b':'zh', 'c':[2, 5, 6]}
[root@ansible-control-node playbooks]#

[root@ansible-control-node playbooks]# cat /etc/ansible/playbooks/advanced_1/create_json_variables.yml
{
 "name": "murali",
 "age": 29,
 "department": "IT",
 "properties": ["Trichy", "Bangalore", "Chennai", "Delhi", 2995],
 "owners":
  {
   "own1": "sachin",
   "own2": "shewag",
   "own3": "dhoni"

  },
 "x": "abc",
 "y": "def"

}
[root@ansible-control-node playbooks]#
