---
- hosts: localhost
  tasks:
    - name: Run with item greater than 5
      command: echo "{{ item }}"
      loop: [0, 2, 3, 4, 5, 6, 7, 9]
      when: item > 5
      
    - name: Start apache2 service
      service:
        name: httpd
        state: started
      register: service_status
      ignore_errors: true
      
    - name: Fail with custom message if httpd service failed to start
      fail:
        msg: "Failed to start httpd service, check httpd service status and review logs"
      when: service_status.failed
      
---
- name: Start http if postfix active
  hosts: centosstream7
  tasks:
    - name: Check postfix status
      command: /usr/bin/systemctl is-active postfix
      ignore_errors: true
      register: result

    - name: Start httpd if postfix is activity
      service:
        name: httpd
        state: restarted
      when: result.rc == 0
