---
- name: Wantedly failing a task
  hosts: localhost
  gather_facts: False

  tasks:
    - name: List out /home
      command: "ls /home"
      register: home_out
      failed_when: home_out.rc == 0

    - name: Fail the task if any errors occured and stop further execution
      command: cat /var/log/server.log
      register: command_output
      failed_when: "'ERROR' in command_output.stdout"

    - name: Install apache2 package
      yum:
        name: httpd
        state: present
      register: result
      failed_when: "'No package matching' in result.msg"

   - name: Verify if epel-release is installed
     command: rpm -q epel-release
     register: verify_results
     failed_when: "'epel-release' not in verify_results.stdout"

   - name: Show epel-release status
     debug:
       msg: "{{ 'epel-release is installed.' if 'epel-release' in verify_results.stdout else 'epel-release is NOT installed.'"
