# The delegate_to directive in Ansible allows you to run a task on a different host than the one being targeted in the playbook. This is useful for scenarios where you want to perform an operation on one host while the main task is executed on another.
- name: Delegate task to localhost
  hosts: webservers
  tasks:
    - name: Get current date from localhost
      command: date
      delegate_to: localhost
      register: date_output

    - name: Display the date
      debug:
        var: date_output.stdout

    - name: Deleting existing .Discovery file
      file:
        path: /etc/ansible/playbooks/advanced_1/Disovery.csv
        state: absent
      delegate_to: localhost
      run_once: true

    - name: Creating .Discovery file
      copy:
        dest: ./Discovery.csv
        content: "hostname,os_family,system_type,distribution_name,distribution_version,uptime"
      delegate_to: localhost
      run_once: true

    - name: Updating discover info in .csv file
      lineinfile:
        path: ./Discovery.csv
        line: "{{inventory_hostname}},{{ansible_os_family}},{{ansible_system}},{{ansible_distribution}},{{ansible_distribution_version}},{{up_time.stdout.split(',')[0].split(' ')[-1]}}"
      delegate_to: localhost
