---
- name: Pause module demo
  hosts: localhost
  vars:
    wait_seconds: "10"

  tasks:
    - name: Wait for {{wait_seconds|int}} second(s)
      ansible.builtin.pause:
        seconds: "{{wait_seconds|int}}"

    - name: Print waited seconds
      ansible.builtin.debug:
        msg: "The task ended"
