---
- name: Creating and Changing file permissions
  hosts: all

  tasks:
    - name: File creation and permission change
      file:
        path: /tmp/abc.txt
        state: touch
        mode: 0755
        owner: testuser
        group: testuser

---
- name: Update SeLinuxType for the file
  hosts: localhost
  tasks:
    - name: Update selinuxtype
      file:
        path: /tmp/ansible_file.txt
        setype: samba_share_t
       # validate the file setype with "ls -lrtZ /tmp/ansible_file.txt" command.

    - name: Set the SELinux Context to it's default Values
      file:
        path: /tmp/testloop.yml
        seuser: _default
        serole: _default
        setype: user_home_t
        selevel: _default
