---
- name: Cron module demo
  hosts: localhost
  become: true

  tasks:
    - name: Updating test cronjob
      ansible.builtin.cron:
        name: "Test cronjob"
        state: present
        minute: "*/2"
        hour: "*"
        month: "*"
        day: "*"
        weekday: "*"
        job: 'logger "ansible-node-test-cron-messagie"'
        
    - name: Adding cronjob for root user
      ansible.builtin.cron:
        name: "Fetch system information"
        state: present
        minute: "*/2"
        hour: "*"
        month: "*"
        day: "*"
        weekday: "*"
        job: "/tmp/scripts/system_info.sh &> /tmp/log/$(hostname)_system_info.log"
