---
- name: mount module demo
  hosts: all
  become: true

  vars:
    mynfs: "190.168.0.200:/nfs/share"
    mountpoint: "/share"
    permission: "0777"
    myopts: 'rw,sync'

  tasks:
    - name: utility present like CentOS
      ansible.builtin.yum:
        name:
          - nfs-utils
          - nfs4-acl-tools
        state: present
      when: ansible_distribution == "CentOS"

    - name: utility present like RedHat
      ansible.builtin.yum:
        name:
          - nfs-utils
          - nfs4-acl-tools
        state: present
      when: ansible_distribution == "RedHat"

    - name: utility present like Debian
      ansible.builtin.yum:
        name:
          - nfs-common
          - nfs4-acl-tools
        state: present
      when: ansible_distribution == "CentOS"

    - name: Check mountpoint exist
      ansible.builtin.file:
        path: "{{ mountpoint }}"
        mode: "{{ permission }}"
        state: directory
        owner: 'root'
        group: 'root'

    - name: mount network share
      ansible.posix.mount:
        src: "{{ mynfs }}"
        path: "{{ mountpoint }}"
        fstype: nfs
        opts: "{{ myopts }}"
        state: mounted
---
- name: mount windows share on Linux demo
  hosts: localhost
  become: true

  vars:
    uri: "//windows-pc/share"
    username: "example@domain"
    password: "password"
    mount_path: /share

  tasks:
    - name: install utility package
      ansible.builtin.package:
        name: cifs-utils
        state: present

    - name: Check mountpoint exist
      ansible.builtin.file:
        name: "{{ mount_path }}"
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Mount network share
      ansible.posix.mount:
        src: "{{ uri }}"
        path: "{{ mount_path }}"
        fstype: cifs
        opts: "username={{ username }}, password={{ password }}"
        state: mounted
