---
- name: mount module demo
  hosts: all
  become: true

  vars:
    mynfs: "190.168.0.200:/nfs/share"
    mountpoint: "/share"
    permission: "0777"
    myopts: 'rw,sync'

  tasks:
    - name: utility present like CentOS
      ansible.builtin.yum:
        name:
          - nfs-utils
          - nfs4-acl-tools
        state: present
      when: ansible_distribution == "CentOS"

    - name: utility present like RedHat
      ansible.builtin.yum:
        name:
          - nfs-utils
          - nfs4-acl-tools
        state: present
      when: ansible_distribution == "RedHat"

    - name: utility present like Debian
      ansible.builtin.yum:
        name:
          - nfs-common
          - nfs4-acl-tools
        state: present
      when: ansible_distribution == "CentOS"

    - name: Check mountpoint exist
      ansible.builtin.file:
        path: "{{ mountpoint }}"
        mode: "{{ permission }}"
        state: directory
        owner: 'root'
        group: 'root'

    - name: mount network share
      ansible.posix.mount:
        src: "{{ mynfs }}"
        path: "{{ mountpoint }}"
        fstype: nfs
        opts: "{{ myopts }}"
        state: mounted
