---
- name: Handlers example playbook
  hosts: localhost
  gather_facts: False

  tasks:
    - name: Install httpd pkgs
      yum:
        name: httpd
        state: present
      notify:
        - start httpd

  handlers:
    - name: start httpd
      service:
        name: httpd
        state: started

---
- name: SELinux policy update
  hosts: localhost
  become: true

  vars:
    selinux_state: "enforcing"
    selinux_policy: "targeted"

  tasks:
    - name: SELinux policy and state
      ansible.posix.selinux:
        state: "{{ selinux_state }}"
        policy: "{{ selinux_policy }}"
      notify: relabel and reboot

  handlers:
    - name: relabel files on next boot
      ansible.builtin.file:
        path: "/.autorelabel"
        state: touch
      when:
        - selinux_state != 'disabled'
      listen: relabel and reboot

    - name: reboot host
      ansible.builtin.reboot:
      listen: relabel and reboot

---
- name: Start and reload the firewall
  hosts: localhost
  tasks:
    - name: Enable http port in firewall
      firewalld:
        service: http
        permanent: yes
        state: enabled
      notify:
        - Reload firewalld

    - name: Start httpd
      service:
        name: httpd
        state: started

  handlers:
    - name: Reload firewalld
      firewalld:
        service: httpd
        state: reloaded
