---
- name: SELinux policy update
  hosts: localhost
  become: true

  vars:
    selinux_state: "enforcing"
    selinux_policy: "targeted"

  tasks:
    - name: SELinux policy and state
      ansible.posix.selinux:
        state: "{{ selinux_state }}"
        policy: "{{ selinux_policy }}"
      notify: relabel and reboot

  handlers:
    - name: relabel files on next boot
      ansible.builtin.file:
        path: "/.autorelabel"
        state: touch
      when:
        - selinux_state != 'disabled'
      listen: relabel and reboot

    - name: reboot host
      ansible.builtin.reboot:
      listen: relabel and reboot
      
---
- name: selinux_permissive module demo
  hosts: all
  become: true
  tasks:
    - name: semanage present
      ansible.builtin.package:
        name: "policycoreutils-python-utils"
        state: present

    - name: Change the httpd_t domain to permissive
      community.general.selinux_permissive:
        name: httpd_t
        permissive: true

---
- name: seboolean module demo
  hosts: localhost
  become: true
  vars:
    selinux_boolean: "httpd_use_nfs"
    selinux_value: true

  tasks:
    - name: package present
      ansible.builtin.package:
        name: "python3-libsemanage"
        state: present

    - name: set SELinux boolean
      ansible.builtin.seboolean:
        name: "{{ selinux_boolean }}"
        state: "{{ selinux_value }}"
        persistent: true
