---
- name: Creating a local user on Client machine
  hosts: all

  tasks:
    - name: user example present
      ansible.builtin.user:
        name: example
        password: "{{ 'password' | password_hash('sha512', 'mysecretsalt') }}"
        groups:
          - wheels
          - admins
        state: present
        shell: "/bin/bash"
        system: no
        create_home: true
        home: "/home/example"
        comment: "Ansible example"
        generate_ssh_key: true
        
    - name: Creating karthi user on Linux Client
      user:
        name: karthi
        create_home: True
        home: /home/karthi
        comment: Kadhal Mannan
        shell: /bin/bash
        
    - name: Update "karthi" users password
      user:
        name: karthi
        update_password: always
        password: "{{ newpassword|password_hash('sha512') }}"
---
- name: Create multi users
  hosts: localhost
  tasks:
    - name: Creating multiple groups
      group:
        name: "{{ item }}"
        state: present
      loop:
        - production
        - development
        - test

    - name: Creating multiple users
      user:
        name: "{{ item.name }}"
        group: "{{ item.group }}"
        state: present
      loop:
        - name: shanthanu
          group: production
        - name: himanshu
          group: development
        - name: ganesh
          group: test

    - name: Create users
      user:
        name: "{{ item }}"
        state: present
      with_items:
        - alice
        - bob
        - charlie
      args:
        shell: /bin/bash  # Common argument for all users

