---
- name: Creating a local user on Client machine
  hosts: all

  tasks:
    - name: Creating karthi user on Linux Client
      user:
        name: karthi
        create_home: True
        home: /home/karthi
        comment: Kadhal Mannan
        shell: /bin/bash
        
    - name: Update "karthi" users password
      user:
        name: karthi
        update_password: always
        password: "{{ newpassword|password_hash('sha512') }}"
