---
- name: Playing with Arithmetice operators based on user input
  hosts: localhost
  gather_facts: False
  vars_prompt:
    - name: a
      prompt: Enter a value
      private: False
    - name: b
      prompt: Enter b value
      private: False

  vars:
    x: 78
    y: "{{x+ 45}}"

  tasks:
    - name: Printing x and y values
      debug:
        msg:
         - "x value is: {{x}}"
         - "y value is: {{y}}"
         - "z value is: {{a|int +x + y|int}}"
         - "{{a}} - {{b}} value is: {{a|int - b|int}}"
         - "{{a}} + {{b}} value is: {{a|int + b|int}}"

---
- name: Input and Output variables
  hosts: localhost
  gather_facts: false
  vars:
    a: 5
    b: 7

  vars_prompt:
    - name: c
      prompt: "Enter c value"
      private: False

    - name: d
      prompt: "Enter d value"
      private: False

  tasks:
    - name: Printing a b c values
      debug:
        msg:
          - "a value is {{a}}"
          - "b value is {{b}}"
          - "c value is {{c}}"
          - "d value is {{d}}"
