[root@ansible-control-node operators]# cat practice_arithmetic_ops2.yml
---
- name: Playing with arithmetic ops
  hosts: localhost
  gather_facts: False
  vars_files:
    - create_variables.yml

  tasks:
    - name: Print a and b value
      debug:
        msg:
         - "a value is: {{a}}"
         - "b value is: {{b}}"

[root@ansible-control-node operators]# locate create_variables.yml
/etc/ansible/playbooks/advanced_1/create_variables.yml
[root@ansible-control-node operators]# cat /etc/ansible/playbooks/advanced_1/create_variables.yml
---
    a: 5
    b: 6
    c: 8
    pkgs:
      'linux': 'top'
      'aix': 'mop'
      'solaris': 'cop'
    x: ['abc', 5, 7.8, {'name':'ganesh'}]
    y: {'a':5, 'b':'zh', 'c':[2, 5, 6]}
[root@ansible-control-node operators]#
