---
- name: Fetching bash version dictionary or map examples
  gather_facts: false
  hosts: localhost

  tasks:
    - name: Fetch bash version
      shell: "bash --version"
      register: bash_out

      # - name: Printing bash version
      # debug: var=bash_out["stdout_lines"]
      # debug: var=bash_out.stdout_lines
      # debug: var=bash_out.get("stdout_lines")

    - set_fact:
        bash_version: "{{ bash_out.stdout.split('\n')[0].split(' ')[3] }}"

    - name: Printing bash version
      debug: var=bash_version
---
- name: Generating hypervisor name
  gather_facts: true  # Ensure that ansible facts are gathered
  hosts: localhost

  tasks:
    - name: Set hypervisor variable
      set_fact: 
        hypervisor: "{{ ansible_hostname.split('-')[0] ~ '-' ~ 'xyzf' ~ ansible_hostname.split('-')[2][:3] }}"
    - name: Show the hypervisor name
      debug:
        msg: "The hypervisor name is {{ hypervisor}}"

---
- name: Generating hypervisor name
  gather_facts: true  # Ensure that ansible facts are gathered
  hosts: localhost

  tasks:
    - name: Set hypervisor variable
      set_fact: 
        hypervisor: "{{ ansible_hostname.split('-')[0] ~ '-' ~ 'xyzf' ~ ansible_hostname.split('-')[2][:3] }}"
        node_heat: >
          {%- if 'm' in ansible_hostname %}
            master
          {%- elif 'h' in ansible_hostname %}
            hot
          {%- elif 'c' in ansible_hostname %}
            cold
          {%- endif %}
        node_master: >
          {%- if 'm' in ansible_hostname %}
            true
          {%- elif 'h' in ansible_hostname %}
            false
          {%- endif %}
    - name: Show the hypervisor name
      debug:
        msg: "The hypervisor name is {{ hypervisor}}"
