---
- name: Fetching bash version dictionary or map examples
  gather_facts: false
  hosts: localhost

  tasks:
    - name: Fetch bash version
      shell: "bash --version"
      register: bash_out

      # - name: Printing bash version
      # debug: var=bash_out["stdout_lines"]
      # debug: var=bash_out.stdout_lines
      # debug: var=bash_out.get("stdout_lines")

    - set_fact:
        bash_version: "{{ bash_out.stdout.split('\n')[0].split(' ')[3] }}"

    - name: Printing bash version
      debug: var=bash_version
---
- name: Generating hypervisor name
  gather_facts: true  # Ensure that ansible facts are gathered
  hosts: localhost

  tasks:
    - name: Set hypervisor variable
      set_fact: 
        hypervisor: "{{ ansible_hostname.split('-')[0] ~ '-' ~ 'xyzf' ~ ansible_hostname.split('-')[2][:3] }}"
    - name: Show the hypervisor name
      debug:
        msg: "The hypervisor name is {{ hypervisor}}"

---
- name: Generating hypervisor name
  gather_facts: true  # Ensure that ansible facts are gathered
  hosts: localhost

  tasks:
    - name: Set hypervisor variable
      set_fact: 
        hypervisor: "{{ ansible_hostname.split('-')[0] ~ '-' ~ 'xyzf' ~ ansible_hostname.split('-')[2][:3] }}"
        node_heat: >
          {%- if 'm' in ansible_hostname %}
            master
          {%- elif 'h' in ansible_hostname %}
            hot
          {%- elif 'c' in ansible_hostname %}
            cold
          {%- endif %}
        node_master: >
          {%- if 'm' in ansible_hostname %}
            true
          {%- elif 'h' in ansible_hostname %}
            false
          {%- endif %}
    - name: Show the hypervisor name
      debug:
        msg: "The hypervisor name is {{ hypervisor}}"

---
- name: Playing with set_facts if else condition to generate hostnames
  hosts: rockylinux9.example1.com, centosstream8.example2.com, centosstream7.example3.com
  tasks:
    - name: Collection of set facts
      set_fact:
        one: "Hello"
        two: "{{ ansible_domain }}"
        three: "{{ ansible_distribution_file_variety[3:6] }}"
        four: "{{ ansible_distribution }}"
        five: "{{ ansible_distribution_major_version }}"
        DC: "{% if ansible_domain == 'example1.com' %}DC1\
             {% elif ansible_domain == 'example2.com' %}DC2\
             {% else %}DC3\
             {% endif %}"

    - name: Displaying set facts one
      debug:
        msg: "{{ one }}"

    - name: Display set fact two
      debug:
        msg: "{{ two }}"

    - name: Display set fact three
      debug:
        msg: "{{ three }}"

    - name: Display set fact four
      debug:
        msg: "{{ four }}"

    - name: Display set fact five
      debug:
        msg: "{{ five }}"

    - name: Display DC name
      debug:
        msg: "Your DC for {{ ansible_hostname }} is {{ DC }}"

    - name: Combine
      debug:
        msg: "{{ one }}-{{ two }}-{{ three }}-{{ four }}{{ five }}-{{ DC }}"
