---
- name: Fetching bash version dictionary or map examples
  gather_facts: false
  hosts: localhost

  tasks:
    - name: Fetch bash version
      shell: "bash --version"
      register: bash_out

      # - name: Printing bash version
      # debug: var=bash_out["stdout_lines"]
      # debug: var=bash_out.stdout_lines
      # debug: var=bash_out.get("stdout_lines")

    - set_fact:
        bash_version: "{{ bash_out.stdout.split('\n')[0].split(' ')[3] }}"

    - name: Printing bash version
      debug: var=bash_version
