---
- hosts: localhost
  tasks:
    - name: Task 1
      shell: uname -a > /tmp/testfile1
      check_mode: true

    - name: Task 2
      shell: uname -a > /tmp/testfile2
      check_mode: false

---
- name: Search a string in a file
  hosts: localhost
  vars:
    mypath: "/etc/ssh/sshd_config"
    mystring: "PasswordAuthentication no"

  tasks:
    - name: Find {{ mystring }} in ssh config file
      ansible.builtin.lineinfile:
        path: "{{ mypath }}"
        line: "{{ mystring }}"
        state: present
      check_mode: true
      register: conf
      failed_when: (conf is failed) or (conf is changed)
