---
- hosts: localhost
  tasks:
    - name: Task 1
      shell: uname -a > /tmp/testfile1
      check_mode: true

    - name: Task 2
      shell: uname -a > /tmp/testfile2
      check_mode: false

---
- name: Search a string in a file
  hosts: localhost
  vars:
    mypath: "/etc/ssh/sshd_config"
    mystring: "PasswordAuthentication no"

  tasks:
    - name: Find {{ mystring }} in ssh config file
      ansible.builtin.lineinfile:
        path: "{{ mypath }}"
        line: "{{ mystring }}"
        state: present
      check_mode: true
      register: conf
      failed_when: (conf is failed) or (conf is changed)
---
- name: Updating ssh file using lineinfile module
  hosts: localhost
  become: true

  tasks:
- name: Check for duplicate values
    lineinfile:
      path: /etc/ssh/sshd_config
      create: false
      regexp: (?i)^\s*LoginGraceTime\s+
      state: absent
    check_mode: true
    changed_when: false
    register: dupes

  - name: Deduplicate values from /etc/ssh/sshd_config
    lineinfile:
      path: /etc/ssh/sshd_config
      create: false
      regexp: (?i)^\s*LoginGraceTime\s+
      state: absent
    when: dupes.found is defined and dupes.found > 1

  - name: Insert correct line to /etc/ssh/sshd_config
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: (?i)^\s*LoginGraceTime\s+
      line: LoginGraceTime 0
      state: present
      insertbefore: ^[#\s]*Match
      validate: /usr/sbin/sshd -t -f %s
