---
- name: Do a Basic install of httpd apache
  hosts: LinuxClient2
  roles:
    - basicinstall
    - python_deps
    - mysql_db
    - flask_web

- name: Do full install of apache
  hosts: LinuxClient1
  roles:
    - fullinstall

- name: App Role Playbook
  roles:
    - httpd
    - time
    - dns
